import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import {
  AlertOctagon,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  BellRing,
  Check,
  CheckCheck,
  CheckCircle,
  ClockFading,
  CloudUpload,
  Download,
  Eye,
  FileImage,
  FileMinus,
  FileSpreadsheet,
  FileText,
  Info,
  Landmark,
  LaptopMinimalCheck,
  Loader,
  LoaderCircle,
  LogOut,
  LucideAngularModule,
  OctagonAlert,
  OctagonX,
  Plus,
  Search,
  SlidersHorizontal,
  Trash2,
  Upload,
  User,
  UserRound,
  Wallet,
  X,
  XCircle,
} from 'lucide-angular';
import { InputFormatDirective } from 'src/app/core/directives/input-format.directive';
import { InputComponent } from 'src/app/shared/ui/input/input.component';
import { ModalComponent } from 'src/app/shared/ui/modal/modal.component';
import { OtpComponent } from 'src/app/shared/ui/otp/otp.component';
import { ToastComponent } from 'src/app/shared/ui/toast/toast.component';
import { ButtonComponent } from './ui/button/button.component';
import { FilenameComponent } from './ui/filename/filename.component';
import { InputDebounceComponent } from './ui/input-debounce/input-debounce.component';
import { MenuComponent } from './ui/menu/menu.component';
import { PaginationComponent } from './ui/pagination/pagination.component';
import { SelectComponent } from './ui/select/select.component';
import { SheetComponent } from './ui/sheet/sheet.component';
import { TableComponent } from './ui/table/table.component';
import { TooltipComponent } from './ui/tooltip/tooltip.component';
import { UploadButtonComponent } from './ui/upload-button/upload-button.component';

@NgModule({
  imports: [
    ButtonComponent,
    CommonModule,
    FormsModule,
    FilenameComponent,
    InputComponent,
    InputDebounceComponent,
    InputFormatDirective,
    LucideAngularModule.pick({
      AlertOctagon,
      AlertTriangle,
      ArrowDown,
      ArrowLeft,
      ArrowRight,
      ArrowUp,
      ArrowUpDown,
      Bell,
      BellRing,
      Check,
      CheckCheck,
      CheckCircle,
      ClockFading,
      CloudUpload,
      Download,
      Eye,
      FileImage,
      FileMinus,
      FileSpreadsheet,
      FileText,
      Info,
      Landmark,
      LaptopMinimalCheck,
      Loader,
      LoaderCircle,
      LogOut,
      OctagonAlert,
      OctagonX,
      Plus,
      Search,
      SlidersHorizontal,
      Trash2,
      Upload,
      User,
      UserRound,
      Wallet,
      X,
      XCircle,
    }),
    MenuComponent,
    ModalComponent,
    OtpComponent,
    PaginationComponent,
    ReactiveFormsModule,
    SelectComponent,
    SheetComponent,
    RouterModule,
    TableComponent,
    ToastComponent,
    TooltipComponent,
    UploadButtonComponent,
  ],
  exports: [
    ButtonComponent,
    CommonModule,
    FilenameComponent,
    FormsModule,
    InputComponent,
    InputDebounceComponent,
    InputFormatDirective,
    LucideAngularModule,
    MenuComponent,
    ModalComponent,
    OtpComponent,
    PaginationComponent,
    ReactiveFormsModule,
    RouterModule,
    SelectComponent,
    SheetComponent,
    TableComponent,
    ToastComponent,
    UploadButtonComponent,
  ],
})
export class SharedModule {}
